//@version=5
indicator('OPEX', overlay=true)
opex = input(title='Monthly Equity, Index Expiration (OPEX)', defval=true)
quarterly = input(title='Quarterly Index Expiration (Q)', defval=true)
spx_roll = input(title='Quarterly SPX Roll (R)', defval=true)
vixex = input(title='Monthly VIX Expiration (VIXEX/VIXPERATION)', defval=true)

opex_line_color = input(title='OPEX Line Color', defval=color.new(color.orange, 30))
opex_label_color = input(title='OPEX Label Color', defval=color.new(color.orange, 30))
opex_label_txt_color = input(title='OPEX Label Text Color', defval=color.new(color.white, 0))

quarterly_line_color = input(title='Quarterly Line Color', defval=color.new(color.red, 30))
quarterly_label_color = input(title='Quarterly Label Color', defval=color.new(color.red, 30))
quarterly_label_txt_color = input(title='Quarterly Label Text Color', defval=color.new(color.white, 0))

spx_roll_line_color = input(title='SPX Roll Line Color', defval=color.new(color.green, 30))
spx_roll_label_color = input(title='SPX Roll Label Color', defval=color.new(color.green, 30))
spx_roll_label_txt_color = input(title='SPX Roll Label Text Color', defval=color.new(color.white, 0))

vixex_line_color = input(title='VIXEX Line Color', defval=color.new(color.purple, 30))
vixex_label_color = input(title='VIXEX Label Color', defval=color.new(color.purple, 30))
vixex_label_txt_color = input(title='VIXEX Label Text Color', defval=color.new(color.white, 0))

vline(TimeIndex, txt, line_color, label_color, label_txt_color) =>
    return_1 = line.new(TimeIndex, low, TimeIndex, high, xloc.bar_time, extend.both, line_color, line.style_dotted, 1)
    l = label.new(TimeIndex, high, txt, xloc.bar_time, yloc.abovebar, label_color, label.style_label_down, label_txt_color, size.normal, text.align_left, txt)
    l


//MONTHLY OPEX DATES
dates_opex = array.new_int(0, timestamp(syminfo.timezone, 2020, 01, 17, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2020, 02, 21, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2020, 03, 20, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2020, 04, 17, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2020, 05, 15, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2020, 06, 19, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2020, 07, 17, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2020, 08, 21, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2020, 09, 18, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2020, 10, 16, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2020, 11, 20, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2020, 12, 18, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2021, 01, 15, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2021, 02, 19, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2021, 03, 19, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2021, 04, 16, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2021, 05, 21, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2021, 06, 18, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2021, 07, 16, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2021, 08, 20, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2021, 09, 17, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2021, 10, 15, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2021, 11, 19, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2021, 12, 17, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2022, 01, 21, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2022, 02, 18, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2022, 03, 18, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2022, 04, 14, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2022, 05, 20, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2022, 06, 17, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2022, 07, 15, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2022, 08, 19, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2022, 09, 16, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2022, 10, 21, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2022, 11, 18, timeframe.isdwm ? 0 : 16, 00, 00))
array.push(dates_opex, timestamp(syminfo.timezone, 2022, 12, 16, timeframe.isdwm ? 0 : 16, 00, 00))

//QUAETERLY OPEX DATES
dates_quarterly = array.new_int(0, timestamp(syminfo.timezone, 2021, 03, 31, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_quarterly, timestamp(syminfo.timezone, 2021, 06, 30, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_quarterly, timestamp(syminfo.timezone, 2021, 09, 30, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_quarterly, timestamp(syminfo.timezone, 2021, 12, 31, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_quarterly, timestamp(syminfo.timezone, 2022, 03, 31, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_quarterly, timestamp(syminfo.timezone, 2022, 06, 30, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_quarterly, timestamp(syminfo.timezone, 2022, 09, 30, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_quarterly, timestamp(syminfo.timezone, 2022, 12, 30, timeframe.isdwm ? 0 : 09, 00, 00))

//VIX EXPIRATION DATES
dates_vixex = array.new_int(0, timestamp(syminfo.timezone, 2021, 01, 20, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_vixex, timestamp(syminfo.timezone, 2021, 02, 17, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_vixex, timestamp(syminfo.timezone, 2021, 03, 17, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_vixex, timestamp(syminfo.timezone, 2021, 04, 21, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_vixex, timestamp(syminfo.timezone, 2021, 05, 19, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_vixex, timestamp(syminfo.timezone, 2021, 06, 16, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_vixex, timestamp(syminfo.timezone, 2021, 07, 21, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_vixex, timestamp(syminfo.timezone, 2021, 08, 18, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_vixex, timestamp(syminfo.timezone, 2021, 09, 15, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_vixex, timestamp(syminfo.timezone, 2021, 10, 20, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_vixex, timestamp(syminfo.timezone, 2021, 11, 17, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_vixex, timestamp(syminfo.timezone, 2021, 12, 22, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_vixex, timestamp(syminfo.timezone, 2022, 01, 19, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_vixex, timestamp(syminfo.timezone, 2022, 02, 16, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_vixex, timestamp(syminfo.timezone, 2022, 03, 15, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_vixex, timestamp(syminfo.timezone, 2022, 04, 20, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_vixex, timestamp(syminfo.timezone, 2022, 05, 18, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_vixex, timestamp(syminfo.timezone, 2022, 06, 15, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_vixex, timestamp(syminfo.timezone, 2022, 07, 20, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_vixex, timestamp(syminfo.timezone, 2022, 08, 17, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_vixex, timestamp(syminfo.timezone, 2022, 09, 21, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_vixex, timestamp(syminfo.timezone, 2022, 10, 19, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_vixex, timestamp(syminfo.timezone, 2022, 11, 16, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_vixex, timestamp(syminfo.timezone, 2022, 12, 21, timeframe.isdwm ? 0 : 09, 00, 00))

//QUAETERLY SPX Roll Dates
dates_spx_roll = array.new_int(0, timestamp(syminfo.timezone, 2020, 03, 12, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_spx_roll, timestamp(syminfo.timezone, 2020, 06, 11, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_spx_roll, timestamp(syminfo.timezone, 2020, 09, 10, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_spx_roll, timestamp(syminfo.timezone, 2020, 12, 10, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_spx_roll, timestamp(syminfo.timezone, 2021, 03, 11, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_spx_roll, timestamp(syminfo.timezone, 2021, 06, 10, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_spx_roll, timestamp(syminfo.timezone, 2021, 09, 09, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_spx_roll, timestamp(syminfo.timezone, 2021, 12, 09, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_spx_roll, timestamp(syminfo.timezone, 2022, 03, 10, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_spx_roll, timestamp(syminfo.timezone, 2022, 06, 09, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_spx_roll, timestamp(syminfo.timezone, 2022, 09, 08, timeframe.isdwm ? 0 : 09, 00, 00))
array.push(dates_spx_roll, timestamp(syminfo.timezone, 2022, 12, 08, timeframe.isdwm ? 0 : 09, 00, 00))

if opex == true
    for i = 0 to array.size(dates_opex) - 1 by 1
        vline(array.get(dates_opex, i), 'OPEX', opex_line_color, opex_label_color, opex_label_txt_color)

if quarterly == true
    for i = 0 to array.size(dates_quarterly) - 1 by 1
        vline(array.get(dates_quarterly, i), 'Q', quarterly_line_color, quarterly_label_color, quarterly_label_txt_color)

if vixex == true
    for i = 0 to array.size(dates_vixex) - 1 by 1
        vline(array.get(dates_vixex, i), 'VIXEX', vixex_line_color, vixex_label_color, vixex_label_txt_color)

if spx_roll == true
    for i = 0 to array.size(dates_spx_roll) - 1 by 1
        vline(array.get(dates_spx_roll, i), 'R', spx_roll_line_color, spx_roll_label_color, spx_roll_label_txt_color)
